#!/usr/bin/env python3
"""
assemble_doc.py — splice the authored sections into the universal document.

The front matter (§1-§3) is hand-written and lives at the top of
docs/10_TAYF_UNIVERSAL_ENGINEERING.md, delimited by the ASSEMBLY marker.
Everything below the marker is regenerated from the section files, so the
document can be rebuilt at any time without touching the hand-written spine.

    python3 assemble_doc.py
"""

import os
import re
import sys

REPO = "/home/hex/tayf"
SCRATCH = os.path.join(REPO, "docs", "sections")
DOC = os.path.join(REPO, "docs", "10_TAYF_UNIVERSAL_ENGINEERING.md")
MARKER = "<!-- ASSEMBLY: everything below is generated by models/assemble_doc.py -->"

# (file, section number, title shown in the document)
# Corrections applied after splicing. Section files are authored independently,
# so anything the spine supersedes must be re-applied on every rebuild.
PATCHES = [
    ('A4["fp16 + LZ4"]', 'A4["delta + int8"]'),
    ("## 4. Optical engineering\n\n",
     "## 4. Optical engineering\n\n"
     "![AIRR ray path](../models/svg/airr_ray_path.svg)\n\n"
     "*The mechanism, drawn from the geometry rather than reproduced from any paper. "
     "Three static elements; the image forms in open air with nothing at its location.*\n\n"
     "![Optical efficiency cascade](../models/svg/efficiency_cascade.svg)\n\n"
     "*Where the light goes. The retroreflector return efficiency \u03b7_RR is the one term "
     "nobody has measured, and it gates every panel-power figure in this document.*\n\n"),
    ('R5 --> R6["fp16 + LZ4"]', 'R5 --> R6["delta + int8"]'),
    ("[ESTIMATE] — the 0.6× ratio is assumed, **never measured on real pose streams**",
     "[SUPERSEDED] — the 0.6× ratio was assumed; **§3.4 measured it and it is wrong** "
     "(zlib/LZ4 *expands* packed pose floats by 2.6%). Use delta+int8: 215 B, 0.104 Mbps"),
    ("Baseline wire bandwidth: fp16 + LZ4, 60 Hz, real WebRTC, measured at the interface "
     "**including headers**",
     "Baseline wire bandwidth: **delta+int8** (per §3.4), 60 Hz, real WebRTC, measured at the "
     "interface **including headers**. The fp16+LZ4 variant is retained only as a control"),
]

FOOTER = open(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                           "doc_footer.md")).read()

SECTIONS = [
    ("10_optics.md",   4, "Optical engineering"),
    ("20_capture.md",  5, "Capture and human representation"),
    ("30_network.md",  6, "Network transmission and the agent layer"),
    ("40_hardware.md", 7, "Hardware, BOM, thermal and the build ladder"),
    ("50_software.md", 8, "Software architecture and the app"),
    ("60_audit.md",    9, "Confidence audit, corrections and open problems"),
]


def demote(md, section_no):
    """Renumber a section's headings under its parent number.

    Authors were told to start at '## '. Rewrite '## X' -> '## N. X' for the
    first heading only, and push every deeper heading down one level so the
    document has a single coherent outline.
    """
    out, first = [], True
    for line in md.split("\n"):
        m = re.match(r"^(#{2,6})\s+(.*)$", line)
        if m:
            depth, text = len(m.group(1)), m.group(2)
            if depth == 2 and first:
                first = False
                continue          # drop it; we emit our own titled heading
            text = re.sub(r"^\d+(\.\d+)*\.?\s+", "", text)
            new_depth = min(depth + 1, 6)
            line = "#" * new_depth + " " + text
        out.append(line)
    return "\n".join(out).strip()


def main():
    if not os.path.isfile(DOC):
        sys.exit(f"missing {DOC}")
    head = open(DOC).read()
    if MARKER in head:
        head = head.split(MARKER)[0].rstrip()

    parts = [head, "", MARKER, ""]
    missing = []
    for fname, num, title in SECTIONS:
        path = os.path.join(SCRATCH, fname)
        if not os.path.isfile(path):
            missing.append(fname)
            parts += [f"## {num}. {title}", "",
                      f"> *Section pending — `{fname}` not yet authored.*", "", "---", ""]
            continue
        body = demote(open(path).read(), num)
        parts += [f"## {num}. {title}", "", body, "", "---", ""]
        print(f"  spliced {fname:16s} -> §{num} {title}")

    body = "\n".join(parts)
    applied = 0
    for old, new in PATCHES:
        if old in body:
            body = body.replace(old, new)
            applied += 1
    body = body.rstrip() + "\n\n" + FOOTER.strip() + "\n"
    open(DOC, "w").write(body)
    print(f"  applied {applied}/{len(PATCHES)} corrections + footer")

    n = len(open(DOC).read().split("\n"))
    print(f"\n{DOC}\n  {n} lines")
    if missing:
        print(f"  PENDING: {', '.join(missing)}")
    return 1 if missing else 0


if __name__ == "__main__":
    sys.exit(main())
